import {test,expect,_electron as electron} from '@playwright/test';
import {mkdtemp,mkdir,writeFile,readFile,appendFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawn} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {Store} from '../core/store.mjs';
import {seedMatureCompanion} from './fixtures/game.mjs';
import {openHome,petControls,revealPetControls} from './helpers.mjs';
const ids=['01a0f1ea-4534-7651-b950-045a233fe631','01a0f5f7-5a51-7483-9fe6-9e028bc08226'];
const stateOf=async page=>(await page.evaluate(()=>window.pawprint.getState())).data;
test('quiet controls retain chat return and approval reminders without voice',async({},info)=>{
 test.skip(process.platform!=='darwin','Hook setup is a macOS preview.');
 const root=await mkdtemp(path.join(os.tmpdir(),'paw-client-helper-ui-')),profile=path.join(root,'profile'),codex=path.join(root,'codex');const state=await seedMatureCompanion(profile);state.settings.language='en';state.settings.petScale=.5;state.settings.clientVoiceMode='dictation';state.settings.workDnd=true;state.settings.activityEnabled=true;state.pets[0].name='Pudding';state.work={version:1,pinned:ids[0],recent:ids.map((threadId,i)=>({threadId,kind:'unknown',at:Date.now()-i*1000,unread:false,bookmark:''}))};const store=new Store(profile);await store.load();await store.save(state);await mkdir(path.join(codex,'sessions'),{recursive:true});const oldHooks={hooks:{SessionStart:[{hooks:[{type:'command',command:'echo KEEP'}]}]}};await writeFile(path.join(codex,'hooks.json'),JSON.stringify(oldHooks));await writeFile(path.join(codex,'session_index.jsonl'),ids.map((id,i)=>JSON.stringify({id,thread_name:i?'Review login error':'Main project task'})).join('\n'));const log=path.join(codex,'sessions','question.jsonl');await writeFile(log,JSON.stringify({type:'session_meta',payload:{id:ids[1]}})+'\n');
 const app=await electron.launch({args:['.'],env:{...process.env,PAWPRINT_TEST_MODE:'1',PAWPRINT_TEST_DATA:profile,PAWPRINT_TEST_CODEX_HOME:codex,PAWPRINT_TEST_LAN:'1'}});
 try{
  const floating=await app.firstWindow(),controls=await petControls(app,{reveal:false}),home=await openHome(app,'work');await expect(home.getByRole('heading',{name:'Work chats',exact:true})).toBeVisible();const bounds=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating')).getBounds());await app.evaluate(({shell})=>{shell.openExternal=async url=>{globalThis.clientHelperOpened=url;};});
  await expect(controls.getByRole('button',{name:/voice|dictate/i})).toHaveCount(0);await expect(home.getByText('Voice & dictation',{exact:true})).toHaveCount(0);expect((await stateOf(home))).not.toHaveProperty('clientVoice');expect(await home.evaluate(()=>typeof window.pawprint.startClientVoice)).toBe('undefined');expect((await home.evaluate(()=>window.pawprint.command({type:'voice-settings',mode:'voice'}))).ok).toBe(false);
  await home.getByRole('button',{name:'Connect',exact:true}).click();await expect(home.getByRole('button',{name:'Disconnect',exact:true})).toBeVisible();expect(JSON.parse(await readFile(path.join(codex,'hooks.json'),'utf8')).hooks.SessionStart).toEqual(oldHooks.hooks.SessionStart);
  const named=JSON.parse(await readFile(path.join(codex,'hooks.json'),'utf8'));expect(named.hooks.PermissionRequest[0].hooks[0].statusMessage).toBe('Pawprint · Approval alerts');
  await floating.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await controls.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await expect(controls.locator('.dock-work').first()).toBeHidden();await expect(controls.locator('.dock-attention')).toHaveCount(0);
  await revealPetControls(app);await floating.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await controls.locator('.dock-return').hover();await floating.waitForTimeout(400);await expect(controls.locator('.dock-return')).toBeVisible();
  expect(await controls.locator('.pet-control-dock').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgba(0, 0, 0, 0)');for(const button of await controls.getByRole('button').all()){const box=await button.boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);}await controls.screenshot({path:info.outputPath('quiet-circles-half-size-cat.png'),omitBackground:true});
  await home.getByRole('button',{name:'Which hooks are Pawprint’s?',exact:true}).click();await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#clientsetup'))).toBe(true);const guide=app.windows().find(w=>w.url().endsWith('#clientsetup'));await expect(guide.locator('.setup-hook-list article')).toHaveCount(7);await guide.getByRole('button',{name:'Open Hooks in client',exact:true}).click();await expect.poll(()=>app.evaluate(()=>globalThis.clientHelperOpened)).toBe('codex://settings');await expect(guide.getByText('The client opened Settings. Select Hooks in its sidebar.')).toBeVisible();await guide.screenshot({path:info.outputPath('english-pawprint-hook-guide.png')});await guide.getByRole('button',{name:'Close guide',exact:true}).click();
  const run=async input=>{const rules=JSON.parse(await readFile(path.join(codex,'hooks.json'),'utf8'));const cmd=rules.hooks[input.hook_event_name].flatMap(g=>g.hooks).find(h=>h.command.includes('--pawprint-attention-v1')).command;const result=await new Promise((resolve,reject)=>{const p=spawn('/bin/sh',['-c',cmd]);let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>resolve({code,out,err}));p.stdin.end(JSON.stringify(input));});expect(result).toEqual({code:0,out:'',err:''});};
  await controls.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await floating.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await expect(controls.locator('.dock-work').first()).toBeHidden();
  const approval={session_id:ids[1],turn_id:'approval-turn',hook_event_name:'PermissionRequest',tool_name:'Bash',tool_input:{command:'echo PRIVATE_COMMAND',description:'PRIVATE_REASON'}};await run(approval);await expect(controls.locator('.dock-work').first()).toBeHidden();await expect(controls.getByRole('button',{name:'Codex needs your attention',exact:true})).toBeVisible();await expect(home.getByTestId('attention-connection')).toContainText('Receiving local client hook events');await expect.poll(async()=>(await stateOf(home)).work.recent.find(r=>r.threadId===ids[1]).attention?.kind).toBe('approval');expect((await stateOf(home)).work.pinned).toBe(ids[0]);expect(JSON.stringify((await stateOf(home)).work)).not.toContain('PRIVATE');await expect(floating.locator('.attention-waiting')).toBeVisible();await floating.screenshot({path:info.outputPath('english-pet-needs-approval.png'),omitBackground:true});
  await controls.getByRole('button',{name:'Codex needs your attention',exact:true}).click();await expect.poll(()=>app.evaluate(()=>globalThis.clientHelperOpened)).toBe(`codex://threads/${ids[1]}`);await expect.poll(async()=>(await stateOf(home)).work.recent.find(r=>r.threadId===ids[1]).attention?.seen).toBe(true);
  await run({...approval,hook_event_name:'PostToolUse',tool_response:{output:'PRIVATE'}});await expect(controls.getByRole('button',{name:'Codex needs your attention',exact:true})).toHaveCount(0);await controls.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await expect(controls.locator('.dock-work').first()).toBeHidden();
  const row=(type,payload)=>JSON.stringify({type,payload,timestamp:new Date().toISOString()})+'\n';await appendFile(log,row('response_item',{type:'function_call',name:'request_user_input_async',call_id:'call-question',arguments:JSON.stringify({questions:[{title:'PRIVATE_QUESTION'}]})}));await appendFile(log,row('response_item',{type:'function_call_output',call_id:'call-question',output:JSON.stringify({accepted:true})}));await expect.poll(async()=>(await stateOf(home)).work.recent.find(r=>r.threadId===ids[1]).attention?.kind).toBe('question');await floating.waitForTimeout(2200);expect((await stateOf(home)).work.recent.find(r=>r.threadId===ids[1]).attention.kind).toBe('question');await home.screenshot({path:info.outputPath('english-client-helpers.png')});
  await appendFile(log,row('event_msg',{type:'user_message',message:`<send_user_message_question_reply>${JSON.stringify([{questionItemId:JSON.stringify(['request_user_input_async','call-question',0]),answer:'PRIVATE_ANSWER'}])}</send_user_message_question_reply>`}));await expect(controls.getByRole('button',{name:'Codex needs your attention',exact:true})).toHaveCount(0);
  const after=await stateOf(home);expect(after.balance).toBe(state.balance);expect(after.ledger).toEqual(state.ledger);expect(after.pets[0].genome).toEqual(state.pets[0].genome);expect(JSON.stringify(after.work)).not.toContain('PRIVATE');expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating')).getBounds())).toEqual(bounds);
  await home.getByRole('button',{name:'Disconnect',exact:true}).click();await expect(home.getByRole('button',{name:'Connect',exact:true})).toBeVisible();expect(JSON.parse(await readFile(path.join(codex,'hooks.json'),'utf8'))).toEqual(oldHooks);
 }finally{await app.close();}
});


test('fresh install starts in English with helpers and recent chats ready without manual connection',async({},info)=>{
 test.skip(process.platform!=='darwin','Automatic hook preparation is macOS only.');
 const root=await mkdtemp(path.join(os.tmpdir(),'paw-fresh-defaults-')),profile=path.join(root,'profile'),codex=path.join(root,'codex');await mkdir(path.join(codex,'sessions'),{recursive:true});
 const db=new DatabaseSync(path.join(codex,'state_5.sqlite'));db.exec('CREATE TABLE threads (id TEXT PRIMARY KEY, name TEXT, cwd TEXT, updated_at INTEGER, archived INTEGER, source TEXT)');db.prepare('INSERT INTO threads VALUES (?,?,?,?,?,?)').run(ids[0],'Continue current project','/projects/pawprint',Math.floor(Date.now()/1000),0,'vscode');db.close();
 const old={hooks:{SessionStart:[{hooks:[{type:'command',command:'echo KEEP'}]}]}};await writeFile(path.join(codex,'hooks.json'),JSON.stringify(old));
 const app=await electron.launch({args:['.'],env:{...process.env,PAWPRINT_TEST_MODE:'1',PAWPRINT_TEST_DATA:profile,PAWPRINT_TEST_CODEX_HOME:codex,PAWPRINT_TEST_LAN:'1'}});
 try{
  await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#home'))).toBe(true);const home=app.windows().find(w=>w.url().endsWith('#home'));await expect(home.getByRole('heading',{name:'My Home',exact:true})).toBeVisible();
  await expect.poll(async()=>(await stateOf(home)).work.recent.length).toBe(1);const state=await stateOf(home);expect(state.settings.language).toBe('en');for(const k of ['connected','activityEnabled','activityTopics','attentionEnabled','quotaEnabled'])expect(state.settings[k]).toBe(true);expect(state.settings.workReminder).toBe('quiet');expect(state.work.recent[0].title).toBe('Continue current project');expect(state.work.recent[0].unread).toBe(false);expect(state.work.recent[0].kind).toBe('unknown');
  const rules=JSON.parse(await readFile(path.join(codex,'hooks.json'),'utf8'));expect(rules.hooks.SessionStart).toEqual(old.hooks.SessionStart);expect(rules.hooks.PermissionRequest[0].hooks[0].statusMessage).toBe('Pawprint · Approval alerts');
  expect(await home.locator('body').innerText()).not.toMatch(/[\u3400-\u9fff]/);await home.screenshot({path:info.outputPath('english-first-launch.png')});
  await home.getByRole('button',{name:'Claim your free first egg',exact:true}).click();await home.getByRole('button',{name:'Meet your companion',exact:true}).click();await home.getByRole('button',{name:'Close dialog',exact:true}).click();
  const controls=await petControls(app);await expect(controls.getByRole('button',{name:'Return to current Codex chat',exact:true})).toBeVisible();
  await app.evaluate(({shell})=>{shell.openExternal=async(url,options)=>{globalThis.freshNav={url,options};};});await controls.getByRole('button',{name:'Return to current Codex chat',exact:true}).click();expect(await app.evaluate(()=>globalThis.freshNav)).toEqual({url:`codex://threads/${ids[0]}`,options:process.platform==='darwin'?{activate:false}:undefined});
 }finally{await app.close();}
});

test('holding cat buttons never opens the home, and buttons work after a client return',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'paw-held-controls-')),profile=path.join(root,'profile'),codex=path.join(root,'codex');const state=await seedMatureCompanion(profile);state.settings.language='en';state.settings.workDnd=true;state.work={version:1,pinned:ids[0],recent:[{threadId:ids[0],kind:'unknown',at:Date.now(),unread:false,bookmark:''}]};const store=new Store(profile);await store.load();await store.save(state);await mkdir(path.join(codex,'sessions'),{recursive:true});
 const app=await electron.launch({args:['.'],env:{...process.env,PAWPRINT_TEST_MODE:'1',PAWPRINT_TEST_DATA:profile,PAWPRINT_TEST_CODEX_HOME:codex,PAWPRINT_TEST_LAN:'1'}});
 try{
  const controls=await petControls(app),floating=app.windows().find(w=>w.url().endsWith('#floating'));
  await app.evaluate(({BrowserWindow,shell,screen})=>{globalThis.controlNavCalls=[];shell.openExternal=async url=>{globalThis.controlNavCalls.push(url);};const d=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#petcontrols')).getBounds();screen.getCursorScreenPoint=()=>({x:d.x+d.width/2,y:d.y+d.height/2});});
  const button=controls.getByRole('button',{name:'Return to current Codex chat',exact:true}),box=await button.boundingBox();await controls.mouse.move(box.x+box.width/2,box.y+box.height/2);await controls.mouse.down();
  await app.evaluate(({app})=>app.emit('activate',{},true));
  expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length)).toBe(2);
  await controls.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await floating.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await controls.waitForTimeout(700);await expect(button).toBeVisible();expect(await app.evaluate(()=>globalThis.controlNavCalls)).toEqual([]);
  await controls.mouse.up();await expect.poll(()=>app.evaluate(()=>globalThis.controlNavCalls.length)).toBe(1);
  await controls.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseleave')));await expect(controls.locator('.dock-work').first()).toBeHidden();
  await revealPetControls(app);await button.click();await expect.poll(()=>app.evaluate(()=>globalThis.controlNavCalls.length)).toBe(2);
  await revealPetControls(app);const list=controls.getByRole('button',{name:'Recent Codex chats',exact:true}),b=await list.boundingBox();await controls.mouse.move(b.x+b.width/2,b.y+b.height/2);await controls.mouse.down();await app.evaluate(({app})=>app.emit('activate',{},true));await controls.waitForTimeout(700);expect(app.windows().some(w=>w.url().endsWith('#home'))).toBe(false);await controls.mouse.up();await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#workmini'))).toBe(true);expect(await app.evaluate(()=>globalThis.controlNavCalls.length)).toBe(2);
  const mini=app.windows().find(w=>w.url().endsWith('#workmini'));await mini.getByRole('button',{name:'Close panel',exact:true}).click();await revealPetControls(app);await button.hover();await controls.mouse.down();await controls.mouse.move(-20,-20);await controls.mouse.up();await controls.waitForTimeout(400);expect(await app.evaluate(()=>globalThis.controlNavCalls.length)).toBe(2);
  await app.evaluate(({app,screen})=>{screen.getCursorScreenPoint=()=>({x:-100000,y:-100000});app.emit('activate',{},true);});await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#home'))).toBe(true);
 }finally{await app.close();}
});
