import { test, expect, _electron as electron } from '@playwright/test';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {petControls,revealPetControls} from './helpers.mjs';
import { Store } from '../core/store.mjs';
import { seedMatureCompanion } from './fixtures/game.mjs';
const ids=['01a0f1ea-4534-7651-b950-045a233fe631','01a0f5f7-5a51-7483-9fe6-9e028bc08226','01a10440-119e-7497-bf8e-14c2b0f2f9a2'];
const stateOf=async page=>(await page.evaluate(()=>window.pawprint.getState())).data;
async function assertEnglish(page){expect(await page.evaluate(()=>[...document.querySelectorAll('*')].flatMap(el=>el.closest('[translate="no"],[data-user-text],script,style')?[]:[...el.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE&&/[\u3400-\u9fff]/.test(n.textContent)).map(n=>n.textContent)))).toEqual([]);}

test('cat opens a separate recent-chat panel, pins and edits notes, then returns with a click-through bookmark',async({},info)=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'paw-work-mini-')),state=await seedMatureCompanion(dir),codex=path.join(dir,'codex');await mkdir(path.join(codex,'sessions'),{recursive:true});
 state.settings.language='en';state.settings.workDnd=true;state.pets[0].name='Pudding';
 await writeFile(path.join(codex,'session_index.jsonl'),ids.map((id,i)=>JSON.stringify({id,thread_name:['Old cost title','Old login title','Old release title'][i]})).join('\n'));
 const dbFile=path.join(codex,'state_5.sqlite'),db=new DatabaseSync(dbFile);db.exec('CREATE TABLE threads (id TEXT PRIMARY KEY, name TEXT, cwd TEXT)');for(let i=0;i<ids.length;i++)db.prepare('INSERT INTO threads VALUES (?,?,?)').run(ids[i],['Investigate token costs','Fix login error','检查发布说明'][i],'/projects/pawprint');db.close();await writeFile(path.join(codex,'.codex-global-state.json'),JSON.stringify({'electron-workspace-root-labels':{'/projects/pawprint':'Pawprint'}}));
 state.work={version:1,pinned:ids[0],recent:ids.map((threadId,i)=>({threadId,at:Date.now()-i*1000,kind:i===1?'running':'completed',unread:true,bookmark:i===0?'Next: check login error':i===2?'A third task note':''}))};
 const store=new Store(dir);await store.load();await store.save(state);
 const app=await electron.launch({args:['.'],env:{...process.env,PAWPRINT_TEST_MODE:'1',PAWPRINT_TEST_DATA:dir,PAWPRINT_TEST_CODEX_HOME:codex,PAWPRINT_TEST_LAN:'1'}});
 try{
  const floating=await app.firstWindow(),controls=await petControls(app);await expect(controls.getByRole('button',{name:'Recent Codex chats',exact:true})).toBeVisible();
  const before=await stateOf(floating),bounds=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating')).getBounds());
  await app.evaluate(({BrowserWindow,shell})=>{shell.openExternal=async url=>{globalThis.openedMiniChat=url;};const old=BrowserWindow.prototype.setIgnoreMouseEvents;BrowserWindow.prototype.setIgnoreMouseEvents=function(ignore,...rest){if(this.getTitle()==='Pawprint Work Bookmark')globalThis.bookmarkIgnoresMouse=ignore;return old.call(this,ignore,...rest);};});
  await controls.getByRole('button',{name:'Return to current Codex chat',exact:true}).click();await expect.poll(()=>app.evaluate(()=>globalThis.openedMiniChat)).toBe(`codex://threads/${ids[0]}`);expect(app.windows().some(w=>w.url().endsWith('#workmini'))).toBe(false);await app.evaluate(()=>{delete globalThis.openedMiniChat;});
  async function panel(){await revealPetControls(app);await controls.getByRole('button',{name:'Recent Codex chats',exact:true}).click();await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#workmini'))).toBe(true);const page=app.windows().find(w=>w.url().endsWith('#workmini'));await expect(page.getByRole('heading',{name:'Recent chats',exact:true})).toBeVisible();return page;}
  let mini=await panel();await expect(mini.locator('.mini-chat')).toHaveCount(3);expect(app.windows().some(w=>/#(home|work)$/.test(w.url()))).toBe(false);
  expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#floating')).getBounds())).toEqual(bounds);
  const placed=await app.evaluate(({BrowserWindow,screen})=>{const w=BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Chats');return {bounds:w.getBounds(),area:screen.getDisplayMatching(w.getBounds()).workArea};});expect(placed.bounds.x).toBeGreaterThanOrEqual(placed.area.x);expect(placed.bounds.y+placed.bounds.height).toBeLessThanOrEqual(placed.area.y+placed.area.height);
  const pinned=mini.locator('.mini-chat.is-pinned');await expect(pinned).toContainText('Next: check login error');await expect(pinned).toContainText('Investigate token costs');await expect(pinned).toContainText('Pawprint');await expect(mini.locator('.mini-chat-list')).toContainText('检查发布说明');expect(await mini.locator('.mini-chat-list').innerText()).not.toContain(ids[0].slice(0,8));await assertEnglish(mini);await mini.screenshot({path:info.outputPath('english-cat-chat-panel.png'),omitBackground:true});
  const second=mini.locator('.mini-chat').nth(1);await second.getByRole('button',{name:'Pin chat',exact:true}).click();await expect(mini.locator('.mini-chat.is-pinned')).toContainText('Fix login error');const renamed=new DatabaseSync(dbFile);renamed.prepare('UPDATE threads SET name=? WHERE id=?').run('Renamed login review',ids[1]);renamed.close();await expect(mini.locator('.mini-chat.is-pinned')).toContainText('Renamed login review',{timeout:12000});await mini.locator('.mini-chat.is-pinned').getByRole('button',{name:'Edit bookmark',exact:true}).click();await mini.getByRole('textbox',{name:'Conversation bookmark',exact:true}).fill('Next: review the login fix');await mini.getByRole('button',{name:'Save note',exact:true}).click();await expect(mini.locator('.mini-chat.is-pinned')).toContainText('Next: review the login fix');
  // This popup may only manage work links and notes; it cannot invoke assistant or economy actions.
  expect((await mini.evaluate(()=>window.pawprint.command({type:'buy-egg'}))).ok).toBe(false);expect(await mini.evaluate(()=>typeof window.pawprint.assistantRun)).toBe('undefined');expect((await mini.evaluate(()=>window.pawprint.openWorkSession('bad?prompt=PRIVATE'))).ok).toBe(false);expect(await app.evaluate(()=>globalThis.openedMiniChat)).toBeUndefined();
  await mini.getByRole('button',{name:'Return to focus chat',exact:true}).click();await expect.poll(()=>app.evaluate(()=>globalThis.openedMiniChat)).toBe(`codex://threads/${ids[1]}`);await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#worknote'))).toBe(true);let note=app.windows().find(w=>w.url().endsWith('#worknote'));await expect(note.getByRole('status')).toContainText('Next: review the login fix');expect(await app.evaluate(()=>globalThis.bookmarkIgnoresMouse)).toBe(true);expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Bookmark').isFocusable())).toBe(false);await assertEnglish(note);await note.screenshot({path:info.outputPath('english-return-bookmark.png'),omitBackground:true});
  expect((await note.evaluate(()=>window.pawprint.command({type:'work-pin',threadId:null}))).ok).toBe(false);await expect.poll(async()=>(await stateOf(floating)).work.recent.find(r=>r.threadId===ids[1]).unread).toBe(false);
  const otherRead=(await stateOf(floating)).work.recent.find(r=>r.threadId===ids[2]).unread;expect(otherRead).toBe(true);
  // Failed opening leaves the user's unread result intact and never shows a successful-return note.
  mini=await panel();await app.evaluate(({shell})=>{shell.openExternal=async()=>{throw new Error('not installed');};});await mini.locator('.mini-chat').filter({hasText:'A third task note'}).getByRole('button',{name:'Return to chat',exact:true}).click();await expect(mini.getByRole('alert')).toContainText('Could not open');expect((await stateOf(floating)).work.recent.find(r=>r.threadId===ids[2]).unread).toBe(true);expect((await stateOf(floating)).workNote).toBeNull();
  await app.evaluate(({shell})=>{shell.openExternal=async url=>{globalThis.openedMiniChat=url;};});
  // Empty bookmarks create no blank bubble; all 160 user characters survive without translation.
  await mini.locator('.mini-chat.is-pinned').getByRole('button',{name:'Edit bookmark',exact:true}).click();await mini.getByRole('textbox',{name:'Conversation bookmark',exact:true}).fill('');await mini.getByRole('button',{name:'Save note',exact:true}).click();await mini.getByRole('button',{name:'Return to focus chat',exact:true}).click();expect((await stateOf(floating)).workNote).toBeNull();
  mini=await panel();const long='检'.repeat(160);await mini.locator('.mini-chat.is-pinned').getByRole('button',{name:'Edit bookmark',exact:true}).click();await mini.getByRole('textbox',{name:'Conversation bookmark',exact:true}).fill(long);await mini.getByRole('button',{name:'Save note',exact:true}).click();await mini.getByRole('button',{name:'Return to focus chat',exact:true}).click();note=app.windows().find(w=>w.url().endsWith('#worknote'));await expect(note.locator('.work-note-text')).toHaveText(long);await assertEnglish(note);expect(await note.locator('.work-note-text').evaluate(el=>el.scrollHeight<=el.clientHeight)).toBe(true);
  await expect.poll(async()=>(await stateOf(floating)).workNote,{timeout:18000}).toBeNull();expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Bookmark').isVisible())).toBe(false);
  const after=await stateOf(floating);expect(after.balance).toBe(before.balance);expect(after.ledger).toEqual(before.ledger);expect(after.pets).toEqual(before.pets);expect(after.settings).toEqual(before.settings);
  mini=await panel();await mini.getByRole('button',{name:'Close panel',exact:true}).click();await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Chats').isVisible())).toBe(false);
  mini=await panel();await mini.keyboard.press('Escape');await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Chats').isVisible())).toBe(false);
  mini=await panel();await app.evaluate(({BrowserWindow,app})=>{app.focus({steal:true});BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Chats').focus();});await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Chats').isFocused())).toBe(true);await app.evaluate(({BrowserWindow})=>{globalThis.workFocusTestWindow=new BrowserWindow({width:240,height:180,title:'Pawprint focus test',show:true});globalThis.workFocusTestWindow.focus();});await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='Pawprint Work Chats').isVisible())).toBe(false);
 }finally{await app.close();}
});
