import {test,expect,_electron as electron} from '@playwright/test';
import {mkdtemp,mkdir,writeFile,appendFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {TRAITS} from '../core/genetics.mjs';
import {Store} from '../core/store.mjs';
import {seedMatureCompanion} from './fixtures/game.mjs';
import {openHome,petControls} from './helpers.mjs';
const ids=['01a0f1ea-4534-7651-b950-045a233fe631','01a0f5f7-5a51-7483-9fe6-9e028bc08226'];
async function setup(){const dir=await mkdtemp(path.join(os.tmpdir(),'paw-work-play-ui-'));const state=await seedMatureCompanion(dir);state.settings.language='en';state.pets[0].name='Pudding';const store=new Store(dir);await store.load();await store.save(state);const codex=path.join(dir,'codex');await mkdir(path.join(codex,'sessions'),{recursive:true});return {dir,codex,state,launch:()=>electron.launch({args:['.'],env:{...process.env,PAWPRINT_TEST_MODE:'1',PAWPRINT_TEST_DATA:dir,PAWPRINT_TEST_CODEX_HOME:codex,PAWPRINT_TEST_LAN:'1'}})};}
const current=async page=>(await page.evaluate(()=>window.pawprint.getState())).data;
async function englishOnly(page){const text=await page.evaluate(()=>{const rows=[],walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const node=walker.currentNode,el=node.parentElement;if(el&&!el.closest('[translate="no"],[data-user-text],style,script')&&el.getClientRects().length&&/[\u3400-\u9fff]/.test(node.textContent))rows.push(node.textContent);}for(const el of document.querySelectorAll('[title],[aria-label],[placeholder]')){if(!el.closest('[translate="no"],[data-user-text]')&&el.getClientRects().length)for(const name of ['title','aria-label','placeholder'])if(/[\u3400-\u9fff]/.test(el.getAttribute(name)||''))rows.push(el.getAttribute(name));}return rows;});expect(text).toEqual([]);}
test('recent chats, pin, bookmark, unread and quiet reminders survive closing the app',async({},info)=>{
 const f=await setup(),files=ids.map((_,i)=>path.join(f.codex,'sessions',`${i}.jsonl`));for(let i=0;i<files.length;i++)await writeFile(files[i],JSON.stringify({type:'session_meta',payload:{id:ids[i],private:'PRIVATE'}})+'\n');
 const event=(type,turn)=>JSON.stringify({type:'event_msg',timestamp:new Date().toISOString(),payload:{type,turn_id:turn,last_agent_message:'PRIVATE reply'}})+'\n';
 let app=await f.launch();try{
  let home=await openHome(app,'work');await expect(home.getByRole('heading',{name:'Work chats',exact:true})).toBeVisible();await home.getByRole('button',{name:'Enable session feedback'}).click();await expect(home.locator('.work-chat')).toHaveCount(2);
  await home.evaluate(id=>window.pawprint.command({type:'work-pin',threadId:id}),ids[0]);const pinned=home.locator('.work-chat.is-pinned');await pinned.getByRole('textbox',{name:'Conversation bookmark'}).fill('Next: check login error');await pinned.getByRole('button',{name:'Save note'}).click();await expect(pinned.getByRole('heading')).toHaveText('Next: check login error');
  await app.evaluate(({shell})=>{shell.openExternal=async url=>{globalThis.openedWork=url;};shell.beep=()=>{globalThis.workBeeps=(globalThis.workBeeps||0)+1;};});
  await home.getByLabel('Reply reminder',{exact:true}).selectOption('sound');await appendFile(files[0],event('task_started','a'));await expect.poll(async()=>(await current(home)).activity.status).toBe('running');await appendFile(files[0],event('task_complete','a'));
  await expect(pinned.getByText('New reply',{exact:true})).toBeVisible();await expect.poll(()=>app.evaluate(()=>globalThis.workBeeps)).toBe(1);
  await home.getByLabel('Do not disturb',{exact:true}).click();await expect(home.getByLabel('Do not disturb',{exact:true})).toBeChecked();await appendFile(files[1],event('task_started','b'));await expect.poll(async()=>(await current(home)).work.recent.find(r=>r.threadId===ids[1])?.kind).toBe('running');await appendFile(files[1],event('task_complete','b'));await expect.poll(async()=>(await current(home)).work.recent.find(r=>r.threadId===ids[1])?.unread).toBe(true);expect(await app.evaluate(()=>globalThis.workBeeps)).toBe(1);
  const floating=app.windows().find(w=>w.url().endsWith('#floating')),controls=await petControls(app);await expect(controls.locator('.work-unread-dot')).toBeVisible();await controls.getByRole('button',{name:'Recent Codex chats',exact:true}).click();await expect.poll(()=>app.windows().some(w=>w.url().endsWith('#workmini'))).toBe(true);await app.windows().find(w=>w.url().endsWith('#workmini')).getByRole('button',{name:'Return to focus chat',exact:true}).click();await expect.poll(()=>app.evaluate(()=>globalThis.openedWork)).toBe(`codex://threads/${ids[0]}`);await expect(pinned.getByText('New reply',{exact:true})).toHaveCount(0);
  await app.evaluate(({Notification})=>{Notification.prototype.show=function(){globalThis.workNotices=(globalThis.workNotices||0)+1;globalThis.workNoticeBody=this.body;};});
  await home.getByLabel('Reply reminder',{exact:true}).selectOption('system');await expect(home.getByLabel('Reply reminder',{exact:true})).toHaveValue('system');await home.getByLabel('Do not disturb',{exact:true}).click();await expect(home.getByLabel('Do not disturb',{exact:true})).not.toBeChecked();await appendFile(files[1],event('task_started','c'));await expect.poll(async()=>(await current(home)).activity.status).toBe('running');await appendFile(files[1],event('task_complete','c'));await expect.poll(()=>app.evaluate(()=>globalThis.workNotices)).toBe(1);expect(await app.evaluate(()=>globalThis.workNoticeBody)).toBe('This reply is finished');await home.getByLabel('Do not disturb',{exact:true}).click();await expect(home.getByLabel('Do not disturb',{exact:true})).toBeChecked();
  await englishOnly(home);await home.screenshot({path:info.outputPath('english-work-chats.png')});await app.close();app=await f.launch();home=await openHome(app,'work');const after=await current(home);expect(after.work.pinned).toBe(ids[0]);expect(after.work.recent.find(r=>r.threadId===ids[0]).bookmark).toBe('Next: check login error');expect(after.work.recent.find(r=>r.threadId===ids[1]).unread).toBe(true);expect(after.settings.workDnd).toBe(true);expect(after.ledger).toEqual(f.state.ledger);expect(JSON.stringify(after.work)).not.toContain('PRIVATE');await englishOnly(home);
 }finally{await app.close();}
});
test('three actual games award growth, unlock room toys, and preserve English and the wallet',async({},info)=>{
 test.setTimeout(180000);const f=await setup();let app=await f.launch();try{
  let home=await openHome(app,'play');await expect(home.getByRole('heading',{name:'Play & room',exact:true})).toBeVisible();await englishOnly(home);await home.screenshot({path:info.outputPath('english-play-room.png')});
  for(const game of ['ball','wand','hide']){
   await home.locator(`.game-choice-${game}`).getByRole('button',{name:'Play 30 seconds'}).click();await expect(home.getByTestId('play-arena')).toBeVisible();await home.getByTestId('play-arena').scrollIntoViewIfNeeded();
   for(let i=0;i<3;i++){
    const r=(await current(home)).playRound;
    if(game==='ball'){
     const ball=await home.getByRole('button',{name:'Throw ball',exact:true}).boundingBox(),target=await home.getByRole('button',{name:'Catch target',exact:true}).boundingBox();await home.mouse.move(ball.x+ball.width/2,ball.y+ball.height/2);await home.mouse.down();await home.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:10});await home.mouse.up();
    }else if(game==='wand'){await home.getByRole('button',{name:'Catch target',exact:true}).hover();}
    else{const names=['Cardboard box','House plant','Curtains','Cushion','Bookshelf','Little bed'];await home.getByTestId('play-arena').getByRole('button',{name:names[r.target.spot],exact:true}).click();}
    await expect.poll(async()=>(await current(home)).playRound?.hits,{timeout:6000}).toBeGreaterThanOrEqual(i+1);await home.mouse.move(12,12);await home.waitForTimeout(1200);
   }
   await englishOnly(home);await home.screenshot({path:info.outputPath(`english-game-${game}.png`)});await expect.poll(async()=>(await current(home)).playRound,{timeout:35000}).toBeNull();expect((await current(home)).pets[0].training.xp[game]).toBeGreaterThanOrEqual(8);
  }
  const state=await current(home);expect(state.pets[0].training.daily.count).toBe(3);expect(state.pets[0].training.bond).toBe(12);expect(state.balance).toBe(f.state.balance);expect(state.ledger).toEqual(f.state.ledger);expect(state.pets[0].genome).toEqual(f.state.pets[0].genome);
  await home.getByRole('button',{name:'Decorate',exact:true}).click();await expect(home.locator('.decor-shelf').getByRole('button',{name:'Practice ball',exact:true})).toBeEnabled();await expect(home.locator('.decor-shelf').getByRole('button',{name:'Training trophy',exact:true})).toBeDisabled();await home.locator('.decor-shelf').getByRole('button',{name:'Practice ball',exact:true}).click();await home.getByTestId('small-room').scrollIntoViewIfNeeded();const room=await home.getByTestId('small-room').boundingBox();await home.mouse.click(room.x+room.width*.55,room.y+room.height*.75);await expect.poll(async()=>(await current(home)).room?.items.some(p=>p.item==='ball')).toBe(true);
  const bed=home.getByTestId('small-room').getByRole('button',{name:'Little bed',exact:true}),b=await bed.boundingBox();await home.mouse.move(b.x+b.width/2,b.y+b.height/2);await home.mouse.down();await home.mouse.move(room.x+room.width*.35,room.y+room.height*.7,{steps:10});await home.mouse.up();await expect.poll(async()=>(await current(home)).room?.items.find(p=>p.item==='bed')?.x).toBe(35);
  await englishOnly(home);await home.screenshot({path:info.outputPath('english-room-decorated.png')});await home.getByRole('button',{name:'Done decorating',exact:true}).click();await app.close();app=await f.launch();home=await openHome(app,'play');const after=await current(home);expect(after.room.items.find(p=>p.item==='bed').x).toBe(35);expect(after.pets[0].training.bond).toBe(12);await englishOnly(home);
 }finally{await app.close();}
});
test('grown companions show extra hiding spots, keepsakes, themes and affectionate room reactions in English',async({},info)=>{
 const f=await setup(),store=new Store(f.dir);await store.load();const state=store.state;const tailless=TRAITS.tail.findIndex(t=>t.absent);state.pets[0].genome.tail=[tailless,tailless];state.pets[0].training={version:1,bond:40,xp:{ball:120,wand:40,hide:40},best:{ball:8,wand:6,hide:5},rounds:25,daily:{date:'2026-09-30',count:3},last:null};await store.save(state);
 const app=await f.launch();try{const home=await openHome(app,'play');await home.getByRole('button',{name:'Decorate',exact:true}).click();await expect(home.locator('.decor-shelf').getByRole('button',{name:'Training trophy',exact:true})).toBeEnabled();await home.getByRole('button',{name:'Moonlit blue',exact:true}).click();await expect(home.getByTestId('small-room')).toHaveClass(/theme-night/);await home.locator('.decor-shelf').getByRole('button',{name:'Training trophy',exact:true}).click();await home.getByTestId('small-room').scrollIntoViewIfNeeded();const room=await home.getByTestId('small-room').boundingBox();await home.mouse.click(room.x+room.width*.68,room.y+room.height*.6);await expect(home.getByTestId('small-room').getByRole('button',{name:'Training trophy',exact:true})).toBeVisible();await home.getByRole('button',{name:'Done decorating',exact:true}).click();await home.getByTestId('small-room').getByRole('button',{name:'Little bed',exact:true}).click();await expect(home.locator('.room-affection')).toBeVisible();await englishOnly(home);await home.screenshot({path:info.outputPath('english-grown-room.png')});
 await home.locator('.game-choice-ball').getByRole('button',{name:'Play 30 seconds'}).click();await home.getByRole('button',{name:'Catch target',exact:true}).click();await expect(home.locator('.play-arena.master .arena-cat.caught')).toBeVisible();expect(await home.locator('.arena-cat.caught').evaluate(el=>getComputedStyle(el).animationName)).toBe('master-catch');await home.getByRole('button',{name:'Leave round',exact:true}).click();
 await home.locator('.game-choice-hide').getByRole('button',{name:'Play 30 seconds'}).click();await expect(home.locator('.hide-spot')).toHaveCount(6);await expect(home.locator('.peek-paw')).toBeVisible({timeout:12000});await expect(home.locator('.peek-tail')).toHaveCount(0);await englishOnly(home);await home.getByRole('button',{name:'Leave round',exact:true}).click();await expect.poll(async()=>(await current(home)).playRound).toBeNull();expect((await current(home)).pets[0].training.bond).toBe(40);
 }finally{await app.close();}
});
