import React,{useState} from 'react';
import {BellRing,Link,Unplug} from 'lucide-react';
import {currentLanguage} from '../i18n/locale.js';
const copy=(en,zh)=>currentLanguage()==='en'?en:zh;
const api=window.pawprint;
export default function ClientHelpers({state,onError}){
  const [busy,setBusy]=useState(false);
  async function action(fn){setBusy(true);try{const r=await fn();if(!r.ok)onError(r.error);}finally{setBusy(false);}}
  const connected=state.settings.attentionEnabled===true,status=state.attention?.status || 'off',ready=['installed','connected'].includes(status);
  return <section className="card client-helpers"><header><h3>{copy('Your client, one paw away','帮你操作客户端')}</h3><p>{copy('Keep track of local approval and question requests, then return to the right chat.','留意本地审批和提问请求，及时返回对应会话。')}</p></header>
    <div className="client-helper-row"><BellRing size={21}/><div><h4>{copy('Approval & answer reminders','审批与回答提醒')}</h4><p>{copy('An amber marker stays when Codex requests approval or asks a question. Click it to return to that chat; Pawprint never approves or answers for you.','Codex 请求审批或提问时，保留黄色标记。点击回到对应会话；Pawprint 不会代你审批或回答。')}</p><small data-testid="attention-connection">{!state.attention?.supported?copy('Hook setup is currently available on macOS.','Hook 设置目前支持 macOS。'):status==='connected'?copy('Receiving local client hook events.','正在接收客户端本地 Hook 事件。'):connected&&ready?copy('Hooks installed. Review and trust the new hooks in your client; reconnect or start a new client turn if needed.','Hook 已安装。请在客户端审核并信任新增 Hook；必要时重连或开始新一轮会话。'):connected?copy('Question reminders are active. Connect hooks for approval alerts; existing rules are preserved.','提问提醒已开启。连接 Hook 可启用审批提醒，会保留其他规则。'):copy('Connect local hooks once. Existing hook rules are preserved.','连接一次本地 Hook，会保留现有规则。')}</small><div className="helper-links"><button className="text-button" onClick={()=>action(()=>api.openClientHelperSettings('hooks'))}>{copy('Open Hooks in client','打开客户端 Hooks')}</button><button className="text-button" onClick={()=>api.showClientGuide('hooks')}>{copy('Which hooks are Pawprint’s?','哪些是 Pawprint 的规则？')}</button></div>{connected&&!ready&&<button className="text-button" onClick={()=>action(api.disconnectAttention)}>{copy('Pause reminders','暂停提醒')}</button>}{connected&&<small>{copy('Approval uses PermissionRequest hooks. Questions also use explicit local question records. Do Not Disturb mutes alerts but keeps the marker.','审批走 PermissionRequest Hook，问题也识别明确的本地提问记录。勿扰只关闭提示，保留标记。')}</small>}</div><button className="button secondary small" disabled={busy||!state.attention?.supported} onClick={()=>action(connected&&ready?api.disconnectAttention:api.connectAttention)}>{connected&&ready?<Unplug size={15}/>:<Link size={15}/>} {copy(connected&&ready?'Disconnect':'Connect',connected&&ready?'断开':'连接')}</button></div>
  </section>;
}
