import React,{useState,useRef} from 'react';import RawText from '../i18n/RawText.jsx';
import {QrCode, Upload, Clipboard} from 'lucide-react';
import Cat from './Cat.jsx';import {t} from '../i18n/locale.js';
const api=window.pawprint;
export default function PetCards({state,onState}){
 const en=state.settings.language==='en',tx=(zh,english)=>en?english:zh;
 const photo=useRef(null),upload=useRef(null);
 const [petId,setPetId]=useState(state.activePetId||state.pets[0]?.id||''),[shared,setShared]=useState(null),[incoming,setIncoming]=useState(null),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const call=async fn=>{setBusy(true);setError('');try{const r=await fn();if(!r.ok)throw Error(r.error);return r.data;}catch(e){setError(e.message);return null;}finally{setBusy(false);}};
 const read=async value=>{const card=await call(()=>api.cardRead(value));if(card){setIncoming(card);setCode(value);}};
 const readImage=async src=>{try{const image=new Image();image.src=src;await image.decode();const scale=Math.min(1,2000/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height),found=(await import('jsqr')).default(pixels.data,canvas.width,canvas.height);if(!found)throw Error(tx('图片里没有找到二维码。','No QR code found in this image.'));await read(found.data);}catch(e){setError(e.message);}};
 const file=async f=>{if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024){setError(tx('请选择小于 10 MB 的 PNG、JPG 或 WebP 图片。','Choose a PNG, JPG or WebP image smaller than 10 MB.'));return;}const reader=new FileReader();reader.onload=()=>void readImage(reader.result);reader.readAsDataURL(f);};
 return <section className="card pet-cards" data-testid="pet-cards" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void file(e.dataTransfer.files[0]);}} onPaste={e=>{const item=[...e.clipboardData.items].find(i=>i.kind==='file');if(item){e.preventDefault();void file(item.getAsFile());}}}>
  <header className="pet-cards-header"><h3>{tx('二维码宠物访问卡','QR pet visiting cards')}</h3><p>{tx('把猫的基因、公开性格和小本领分享给朋友。拖入或粘贴二维码图片即可预览，不用服务器或摄像头。','Share genes, public temperament and tricks. Drop or paste a QR image to preview; no server or camera needed.')}</p></header>
  <div className="pet-card-actions"><select aria-label={tx('选择分享的猫','Choose a cat to share')} value={petId} onChange={e=>{setPetId(e.target.value);setShared(null);}}>{state.pets.map(p=><option translate="no" key={p.id} value={p.id}>{p.name}</option>)}</select><button className="button secondary" disabled={busy||!petId} onClick={async()=>{const r=await call(()=>api.cardCreate(petId));if(r)setShared(r);}}><QrCode size={16}/>{tx('生成二维码','Create QR code')}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>upload.current?.click()}><Upload size={16}/>{tx('选择二维码图片','Choose QR image')}</button><input ref={upload} hidden type="file" accept="image/png,image/jpeg,image/webp" aria-label={tx('导入二维码图片','Import QR image')} onChange={e=>{void file(e.target.files[0]);e.target.value='';}}/><button className="button secondary" disabled={busy} onClick={async()=>{const image=await call(()=>api.cardClipboard());if(image)await readImage(image);}}><Clipboard size={16}/>{tx('读取剪贴板图片','Read clipboard image')}</button></div>
  {shared&&<div className="pet-card-share"><img src={shared.png} alt={tx('宠物访问卡二维码','Pet visiting card QR code')} width="240" height="240"/><div><strong><RawText>{shared.card.pet.name}</RawText></strong><p>{shared.card.temperament.map(t).join(' · ')}</p><button className="button secondary" onClick={()=>call(()=>api.cardCopy(petId))}>{tx('复制二维码图片','Copy QR image')}</button><details><summary>{tx('访问卡文字码','Card text code')}</summary><textarea aria-label={tx('访问卡文字码','Card text code')} readOnly value={shared.code}/></details></div></div>}
  <details><summary>{tx('粘贴访问卡文字码','Paste a card text code')}</summary><textarea aria-label={tx('粘贴访问卡文字码','Paste a card text code')} value={code} onChange={e=>setCode(e.target.value)}/><button className="button secondary" onClick={()=>read(code)}>{tx('预览访问卡','Preview card')}</button></details>
  {incoming&&<div className="pet-card-preview" data-testid="pet-card-preview"><div className="card-photo" ref={photo}><Cat genome={state.pets.find(p=>p.id===petId)?.genome||incoming.pet.genome}/><Cat genome={incoming.pet.genome}/></div><div><h4><RawText>{incoming.pet.name}</RawText></h4><p>{incoming.temperament.map(t).join(' · ')}</p><p>{tx('访问卡是分享时的快照，不包含聊天、主人资料或模型配置。访客不占入住名额，不参与繁育和交易。','Cards are snapshots without chats, owner details or model settings. Visitors use no house slot and cannot breed or trade.')}</p><button className="button primary" disabled={busy} onClick={async()=>{const result=await call(()=>api.cardVisit(code));if(result)onState(result);}}>{tx('邀请来玩 5 分钟','Invite for 5 minutes')}</button><button className="button secondary" onClick={async()=>{photo.current.scrollIntoView({block:'center'});await new Promise(requestAnimationFrame);const r=photo.current.getBoundingClientRect();await call(()=>api.cardPhoto({x:Math.round(r.x),y:Math.round(r.y),width:Math.round(r.width),height:Math.round(r.height)}));}}>{tx('复制猫咪合照','Copy cat photo')}</button></div></div>}
  {(state.cardVisitors||[]).map(v=><div className="pet-card-actions" key={v.id}><span>{v.pet.name} · {tx('正在来访','Visiting')}</span><button className="button secondary small" onClick={async()=>{const r=await call(()=>api.cardDismiss(v.id));if(r)onState(r);}}>{tx('送它回家','Send home')}</button></div>)}
  {!!state.cardFootprints?.length&&<p className="muted small-copy">{tx('最近的脚印：','Recent pawprints: ')}{state.cardFootprints.slice(-5).map(v=>v.name).join(' · ')}</p>}
  {error&&<p role="alert">{error}</p>}
 </section>;
}
